Repository AndreiSorokin/myEvents, pull requests merged in 2024-10, with the labels that each got.

#17 PR - Test/unit testing
  .gitignore
  server/https/user.rest
  server/src/__tests__/eventService.test.ts
  server/src/__tests__/helper/userHelper.ts
  server/src/__tests__/userService.test.ts
  server/src/services/eventService.ts
  server/src/services/userService.ts
Labels: ready for review

#21 Authorization and authentication
  client/components.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.tsx
  client/src/api/apiSlice.ts
  client/src/api/authSlice.ts
  client/src/api/userSlice.ts
  client/src/components/Navbar.tsx
  client/src/components/auth/Login.tsx
  client/src/components/auth/ResetPasswordForm.tsx
  client/src/components/auth/ResetPasswordModal.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/confetti.tsx
  client/src/components/user/CreateAccountModal.tsx
  client/src/components/user/CreateUser.tsx
  client/src/index.css
  client/src/lib/utils.ts
  client/src/main.tsx
  client/src/misc/auth.ts
  client/src/misc/user.ts
  client/src/redux/store.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/vite.config.ts
  server/README.md
  server/package-lock.json
  server/package.json
  server/src/__tests__/eventService.test.ts
  server/src/__tests__/userService.test.ts
  server/src/controllers/authController.ts
  server/src/controllers/userController.ts
  server/src/models/event.ts
  server/src/models/user.ts
  server/src/routes/authRoutes.ts
  server/src/routes/userRoutes.ts
  server/src/services/authService.ts
  server/src/services/userService.ts
  server/src/utils/emailService.ts
Labels: in progress

#20 Update: Set up RAG for project
  server/https/event.rest
  server/package.json
  server/src/config/eventSearchHuggingFace.ts
  server/src/controllers/eventController.ts
  server/src/interfaces/IEvent.ts
  server/src/langchain/agent.ts
  server/src/langchain/eventSearchChain.ts
  server/src/langchain/summarizeService.ts
  server/src/models/event.ts
  server/src/models/location.ts
  server/src/routes/eventRoutes.ts
  server/src/services/eventService.ts
  server/src/utils/connectMongoose.ts
  server/src/utils/eventSeeding.ts
  server/src/utils/locationOrganizerSeeding.ts
  server/src/utils/locationValidation.ts
Labels: enhancement
